version: "2.0"
services:
        nexus:
                image: sonatype/nexus3:latest
                container_name: nexus
                ports:
                        - 8081:8081
                volumes:
                        - ./nexus/nexus-data:/nexus-data:rw
        nginx:
                image: nginx
                container_name: nginx
                tty: true
                depends_on:
                        - nexus
                links:
                        - nexus
                ports:
                        - 443:443
                        - 8123:8123
                volumes:
                        - ./nginx/files/nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx/files/registry.conf:/etc/nginx/sites-enabled/registry.conf
